### ISSUE TITLE
Sintesis de calidad

### ISSUE THREAD

**Issue by NoeliaGlez** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-NoeliaGlez#1]
[Sintesis gestion de calidad.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-NoeliaGlez/files/12704099/Sintesis.gestion.de.calidad.pdf)

**Comment by EdwinOrtiz1412** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
